name: flutter_firebase_database_geolocation
description: A new flutter plugin project.
version: 0.0.1
author: Bram Vanbilsen
homepage:

flutter:
  plugin:
    androidPackage: com.vanbilsen.bram.firebase.database.geolocation.flutterfirebasedatabasegeolocation
    pluginClass: FlutterFirebaseDatabaseGeolocationPlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^0.3.0
  geohash: ^0.1.1

environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=1.20.1 <3.0.0'
