name: flutter_firebase_database_geolocation
description: A new flutter plugin project.
version: 0.0.1
author: Bram Vanbilsen
homepage:

flutter:
  plugin:
    androidPackage: com.vanbilsen.bram.firebase.database.geolocation.flutterfirebasedatabasegeolocation
    pluginClass: FlutterFirebaseDatabaseGeolocationPlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_database: "^0.1.0"
  geohash: "^0.1.1"
